### recuperar peliculas
GET http://localhost:1234/movies

### recuperar peliculas por id
GET http://localhost:1234/movies/64f25b3b-7259-11ef-8902-0800272635f7

### recuperar por genero
GET http://localhost:1234/movies?genre=sci-FI

### crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1999,
    "director": "Lana Wachowski",
    "duration": 136,
    "poster": "https://i.ebayimg.com/images/g/QFQAAOSwAQpfjaA6/s-l1200.jpg",
    "genre": [
      "Crime",
      "Drama"
    ]
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/15b8b604-fef0-41d6-95da-75226452169f
Content-Type: application/json

{
    "year": 2020 
}

### Borrar usando id
DELETE http://localhost:1234/movies/154cc4e6-725e-11ef-8902-0800272635f7